### ISSUE TITLE
WordPress plugin boilerplate választás

### ISSUE THREAD

**Issue by bolint** [bolint/wp-szechenyi2020-infoblokk#1]
Kellene választani egy jó alap boilerplatet, amivel készüljön a plugin.
Ezek az ajánlások: https://developer.wordpress.org/plugins/plugin-basics/best-practices/#boilerplate-starting-points

**Comment by ocReaper** [comment]
https://github.com/bayareawebpro/wp-lumen-plugin-framework

**Comment by bolint** [comment]
> https://github.com/bayareawebpro/wp-lumen-plugin-framework
> https://github.com/ahmadawais/create-guten-block

Ha csak egyet teszel be, akkor lehet szavazni! ;)

**Comment by ocReaper** [comment]
https://github.com/ahmadawais/create-guten-block
