### ISSUE TITLE
Add option to change language

### ISSUE THREAD

**Issue by bolint** [bolint/wp-szechenyi2020-infoblokk#8]
Use should choose between Hungarian and English.

The English version of the "infoblokk" is available here: https://bolint.hu/wp-content/uploads/2020/10/infoblokk.zip

**Comment by ocReaper** [comment]
As I see this issue is irrelevant because the user can upload whichever version he/she wants to use via #13

**Comment by bolint** [comment]
> As I see this issue is irrelevant because the user can upload whichever version he/she wants to use via #13

Yes, it's irrelevent now.
